### ISSUE TITLE
Connect heroku to gamasak/pooper github repository

### ISSUE THREAD

**Issue by cawak** [gamasak/pooper#3]
This will enable us to deploy automatically to heroku once we merge with the master. Currently this process is automatic because we basically don't have a pipeline.

What is needed to be done:
- [x] Do the changes in heroku (should be very easy).
- [x] We need to push some code with different text such as "Hello gamasak!!!" (instead of the existing "Hello, world!") to check if it works.

**Comment by AlexGr2** [comment]
Code was deployed and continually updated heroku app for gamasak

**Comment by cawak** [comment]
Great! It works now.
